name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    branches:
      - main
env:
  JULIA_PKG_USE_CLI_GIT: true
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.9'
          - 'nightly'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      # - uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #       ssh-private-key: ${{ secrets.COOLWALKSUTILS_PRIVATE_KEY }}
      # - name: Clone CoolWalksUtils.jl
      #   run: git clone https://github.com/SuperGrobi/CoolWalksUtils.jl ../CoolWalksUtils.jl
      # - name: Install CoolWalksUtils repo
      #   shell: julia --color=yes --project=. {0}
      #   run: using Pkg; Pkg.add(path="../CoolWalksUtils.jl")
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.COOLWALKSREGISTRY_PRIVATE_KEY }}
      - name: Add CoolWalks Registry
        shell: julia --color=yes --project=. {0}
        run: using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/SuperGrobi/CoolWalksRegistry"))
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.COOLWALKSUTILS_PRIVATE_KEY }}
      - name: Clone CoolWalksUtils.jl
        run: git clone https://github.com/SuperGrobi/CoolWalksUtils.jl
      - name: Install CoolWalksUtils repo
        run: julia --project=docs -e 'using Pkg; Pkg.add(path="./CoolWalksUtils.jl")'
      - uses: julia-actions/julia-buildpkg@v1
        with:
            project: 'docs'
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using TreeLoaders
            DocMeta.setdocmeta!(TreeLoaders, :DocTestSetup, :(using TreeLoaders); recursive=true)
            doctest(TreeLoaders)'
